org.gradle.jvmargs=-Xmx2G

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.19.5
fabric_version=0.116.17+1.21.1
loom_version=1.10.5
spell_engine_version=1.10.8

mod_version=1.0.1
maven_group=com.betterspellcasting
archives_base_name=better-spell-casting-fabric
loader_name=fabric
